name: Build & Test

on:
  push:
    branches: [ wizards ]
  pull_request:
    branches: [ wizards ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore Lidgren.Network.MultiTarget/Lidgren.Network.MultiTarget.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Lidgren.Network.MultiTarget/Lidgren.Network.MultiTarget.csproj

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        targetframework: [net45, net48, netcoreapp3.1]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Test
      run: dotnet test --configuration Release --framework ${{ matrix.targetframework }} UnitTests.Core/UnitTests.Core.csproj 
